version: '3.7'
services:
  mysql:
    image: mysql
    restart: no
    ports:
      - 3306:3306
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: tin_final_project
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    volumes:
      - ./baza-danych:/var/lib/mysql